# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Asennusohje"
license = "MIT"
licenselink = "https://github.com/sakumatto/hugo_theme-asennusohje/blob/master/LICENSE.md"
description = "A simple wiki for showing documents"
homepage = "https://github.com/sakumatto/hugo_theme-asennusohje"
tags = ['minimal', 'wiki-like', 'documentation']
features = ['wiki-like', 'responsive', 'minimal', 'shortcode', 'clean', 'boxes', 'i18n']
min_version = "0.57"

[author]
  name = "Saku Mättö"
#  homepage = "https://sakumatto.fi/"
#  repo = "https://github.com/sakumatto/hugo_theme-asennusohje"

# based on [author]
#  name = "Olivier DOSSMANN"
#  homepage = "https://olivier.dossmann.net/"
#  repo = "https://github.com/blankoworld/hugo_theme_adam_eve"
